version: '3.8'

services:
    # MySQL Database
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - mynetwork
        ports:
            - "3307:3306"

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
            PMA_ARBITRARY: 1
        ports:
            - "8082:80"
        networks:
            - mynetwork

    # PHP-FPM for Laravel
    crm-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: crm-app
        volumes:
            - ./storage/app/public:/app/storage/app/public
            - ./:/var/www/html  # Монтируем всю папку проекта
        networks:
            - mynetwork
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${MYSQL_DATABASE}
            - DB_USERNAME=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - PHP_FPM_LISTEN=9000
        depends_on:
            - db
        command: >
            bash -c "mkdir -p /var/www/html/bootstrap/cache &&
            chown -R www-data:www-data /var/www/html &&
            chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
            php-fpm -F"

    # Nginx for Laravel
    nginx:
        image: nginx:alpine
        container_name: crm-nginx
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        networks:
            - mynetwork
        depends_on:
            - crm-app

volumes:
    db_data:

networks:
    mynetwork:
        driver: bridge
